<h1>Homework 2</h1>
In this notebook there are the activities related to the second homework and, as with the first homework, feel free to use the web to find the solutions to any of these problems. Also, the bonus questions are not mandatory but, if you happen to have the time, try them out too!<br>



<h1>numpy</h1>
Exercise 1: show that now you can import libraries by importing pandas, numpy and matplotlib.

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

Exercise 2: Will the following code block work?  

It will work, because 3,3 array and 3,1 array are compatible.

In [2]:
# This creates a 3x3 array of random numbers ranging from 0 to 1
array1 = np.random.random((3, 3))
array2 = np.random.random((3, 1))

np.add(array1,array2)



array([[0.18039639, 0.44734631, 0.28334081],
       [0.96701209, 0.44227038, 0.39053677],
       [0.30942323, 0.89322933, 0.52405616]])

Exercise 3: What about now?

This time it won't work because 3,3 array and 3,2 array aren't compatible.

In [8]:
# This creates a 3x3 array of random numbers ranging from 0 to 1
array3 = np.random.random((3, 3))
array4 = np.random.random((3, 2))

np.add(array3,array4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

Exercise 4: by inspecting the arrays 1 to 4 can you figure out why one operation worked and another one didn't? (hint: check their values and shape)

It worked in first block of code because 3,3 array and 3,1 array are compatible.
Second time it didn't because 3,3 array and 3,2 array aren't compatible.

Exercise 5: Using the function to create an array of random numbers [np.random.random](https://numpy.org/doc/stable/reference/random/generated/numpy.random.random.html) how can you modify the code (as in the cells above) so that the numbers will vary between 0 and 100 instead of 0 and 1? And how can you modify the shape of the function?

In [20]:
def randomise(start, end, rows, columns):
    return np.random.randint(start, end, size=(rows, columns))
random_matrix = randomise(0, 100, 4,9)

Exercise 6: Using the array defined on the exercise above, use [np.where](https://numpy.org/doc/stable/reference/generated/numpy.where.html) to find the positions the values that are larger than 50 (or feel free to pick any other number).

In [25]:
np.where(random_matrix > 50)

(array([0, 0, 0, 1, 2, 2, 2, 2, 2, 3, 3], dtype=int64),
 array([0, 1, 4, 7, 0, 1, 2, 3, 5, 5, 6], dtype=int64))

<h1>Pandas </h1>
There are two datasets on available to this work one is the pokemon dataset we explored in the lectured and the other one is the same dataframe but, for the sake of a nice story, let us say it was sabotaged by team rocket.

Exercise 1: open both dataframes supplied using [pd.read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) (and don't forget to assign them to different objects).

In [27]:
pokemon_df = pd.read_csv("Pokemon.csv")
pokemon_sabotage_df = pd.read_csv("Pokemon_sabotage.csv")

       #                   Name   Type 1  Type 2  Total    HP  Attack  \
0      1              Bulbasaur    Grass  Poison    318  45.0      49   
1      2                Ivysaur    Grass  Poison    405  60.0      62   
2      3               Venusaur    Grass  Poison    525  80.0      82   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80.0     100   
4      4             Charmander     Fire     NaN    309  39.0      52   
..   ...                    ...      ...     ...    ...   ...     ...   
795  719                Diancie     Rock   Fairy    600  50.0     100   
796  719    DiancieMega Diancie     Rock   Fairy    700  50.0     160   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80.0     110   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80.0     160   
799  721              Volcanion     Fire   Water    600  80.0     110   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       49.0       65     65.0   45.0           1      False

Exercise 2: Using [pd.isna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html) check how many missing numbers are in each dataframe.

In [32]:
pokemon_table = pokemon_df.isna().sum()
pokemon_total = pokemon_df.isna().sum().sum()
sabotage_table = pokemon_sabotage_df.isna().sum()
sabotage_total = pokemon_sabotage_df.isna().sum().sum()
print(pokemon_table)
print(pokemon_total)
print(sabotage_table)
print(sabotage_total)

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64
386
#               0
Name            2
Type 1          1
Type 2        387
Total           0
HP              3
Attack          0
Defense         1
Sp. Atk         0
Sp. Def         1
Speed           4
Generation      0
Legendary       0
dtype: int64
399


Exercise 3: Two of the main ways to deal with missing data is [pd.dropna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html) and [pd.fillna](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html). How are these methods different from each other in how they deal with the missing data? Which, if any, would you use on the dataset? Why?

In [ ]:
#pd.dropna() will delete empty cells, where is pd.fillna() will fill them with data

From now on we will only be working with the main (non sabotaged dataframe).<br>

Exercise 4: to free up memory delete the sabotaged dataframe. Bonus: before deleting find a way to check how much space in memory the dataframes occupy. [hint](https://stackoverflow.com/questions/449560/how-do-i-determine-the-size-of-an-object-in-python)

In [33]:
import sys
sys.getsizeof(pokemon_sabotage_df)
del pokemon_sabotage_df

199279

Exercise 5: Create a new column that contains the sum of the Attack, speed and defense stats.

In [37]:
pokemon_df["ASD"] = pokemon_df["Attack"] + pokemon_df["Speed"] + pokemon_df["Defense"]
pokemon_df["ASD"]

0      143
1      185
2      245
3      303
4      160
      ... 
795    300
796    380
797    240
798    300
799    300
Name: ASD, Length: 800, dtype: int64

Exercise 6: Find out the mean value of the attack, speed, defense columns and the new column that was created above.

In [39]:
mean_attack = pokemon_df["Attack"].mean()
mean_speed = pokemon_df["Speed"].mean()
mean_defense = pokemon_df["Defense"].mean()
mean_asd = pokemon_df["ASD"].mean()


print(mean_attack)
print(mean_speed)
print(mean_defense)
print(mean_asd)

79.00125
68.2775
73.8425
221.12125


Exercise 7: Find out how many pokemon have above average stats in the attack, speed, defense and the new column. Bonus: Do the pokemon with above average stats have a preffered type?

In [55]:
new_df = pokemon_df[(pokemon_df["Attack"]> mean_attack)&(pokemon_df["Speed"]> mean_speed) & (pokemon_df["Defense"]> mean_defense) & (pokemon_df["ASD"]>mean_asd) ]



print(new_df.value_counts("Type 1").sum()) #Type 1 is preffered type
print(new_df.value_counts("Type 2").sum())

147
100


Super bonus: There are many platforms out there that contain different tools to boost your learning. Then for the super bonus create an account on [kaggle](https://www.kaggle.com/) and complete the courses
[intro to programming](https://www.kaggle.com/learn/intro-to-programming) and [intro to python](https://www.kaggle.com/learn/python) courses. All kaggle courses are free of charge and offer a [certificate](https://www.kaggle.com/learn-course-certificates) !